# Generated by Django 5.0.1 on 2024-01-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('key', models.SlugField(max_length=100, primary_key=True, serialize=False, verbose_name='Indentificador')),
                ('value', models.TextField(verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
            ],
            options={
                'verbose_name': 'Variavel',
                'verbose_name_plural': 'Variaveis',
                'ordering': ['key'],
            },
        ),
    ]
