# Generated by Django 5.0.1 on 2024-01-05 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('name', models.CharField(max_length=300, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='BankManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('name', models.CharField(max_length=300, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Gerente de Banco',
                'verbose_name_plural': 'Gerentes de Banco',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('name', models.CharField(max_length=300, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Negócio',
                'verbose_name_plural': 'Negócios',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('name', models.CharField(max_length=300, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='CreditAnalyst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('name', models.CharField(max_length=300, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Analista de Crédito',
                'verbose_name_plural': 'Analistas de Crédito',
            },
        ),
        migrations.CreateModel(
            name='DocAnalyst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('name', models.CharField(max_length=300, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Analista Documental',
                'verbose_name_plural': 'Analistas Documentais',
            },
        ),
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('name', models.CharField(max_length=300, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Planejador',
                'verbose_name_plural': 'Planejadores',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('name', models.CharField(max_length=300, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('branch', models.CharField(max_length=300, verbose_name='Agência')),
                ('available_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Crédito Disponível')),
                ('credit_line', models.CharField(blank=True, max_length=300, null=True, verbose_name='Linha de Crédito')),
                ('client_status', models.CharField(blank=True, choices=[('analise-negativa', 'Análise Negativa'), ('atualizado', 'Atualizado'), ('cobrar-gn', 'Cobrar GN'), ('consultar-rating', 'Consultar Rating'), ('credito-aprovado', 'Crédito Aprovado'), ('desistiu', 'Desistiu'), ('faleceu', 'Faleceu'), ('falta-doc', 'Falta Doc'), ('fazer-limite', 'Fazer Limite'), ('fazer-projeto', 'Fazer Projeto'), ('inativo', 'Inativo'), ('operacao-concluida', 'Operação Concluída'), ('processo-no-banco', 'Processo no Banco'), ('processo-parado', 'Processo Parado'), ('prospect', 'Prospect'), ('sem-interesse', 'Sem Interesse')], max_length=300, null=True, verbose_name='Status')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback')),
                ('risk_alert', models.TextField(blank=True, null=True, verbose_name='Alerta de Risco')),
                ('credit_info', models.TextField(blank=True, null=True, verbose_name='Informações de Crédito')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('credit_due_date', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento do Crédito')),
                ('credit_insurance', models.CharField(blank=True, max_length=300, null=True, verbose_name='Seguro de Crédito')),
                ('project_info', models.TextField(blank=True, null=True, verbose_name='Informações do Projeto')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.bank', verbose_name='Banco')),
                ('bank_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.bankmanager', verbose_name='Gerente de Banco')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.business', verbose_name='Negócio')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.client', verbose_name='Cliente')),
                ('credit_analyst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.creditanalyst', verbose_name='Analista de Crédito')),
                ('doc_analyst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.docanalyst', verbose_name='Analista Documental')),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.planner', verbose_name='Planejador')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
    ]
