# Generated by Django 5.0.1 on 2024-01-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AlterField(
            model_name='process',
            name='date',
            field=models.CharField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
